DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS budgets;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS ai_call_log;
DROP TABLE IF EXISTS user_settings;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

CREATE TABLE user_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  default_currency VARCHAR(8) NOT NULL DEFAULT 'USD',
  month_start_day INT NOT NULL DEFAULT 1,
  receipt_reminders TINYINT NOT NULL DEFAULT 1,
  budget_alerts TINYINT NOT NULL DEFAULT 1,
  weekly_report TINYINT NOT NULL DEFAULT 0,
  ai_assist_enabled TINYINT NOT NULL DEFAULT 1,
  ai_api_key_encrypted VARCHAR(2048),
  ai_api_key_last4 VARCHAR(8),
  ai_base_url VARCHAR(255),
  ai_model VARCHAR(100),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_user_settings_user ON user_settings(user_id);

CREATE TABLE ai_call_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  operation VARCHAR(32) NOT NULL,
  model VARCHAR(100),
  base_url VARCHAR(255),
  prompt_tokens INT,
  completion_tokens INT,
  total_tokens INT,
  latency_ms INT,
  success TINYINT NOT NULL,
  error_code VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_call_log_user_created ON ai_call_log(user_id, created_at);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL,
  icon VARCHAR(120),
  color VARCHAR(40),
  description VARCHAR(500),
  is_default TINYINT DEFAULT 0,
  usage_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_categories_user_name_active ON categories(user_id, name, deleted_at);
CREATE INDEX idx_categories_user_deleted_name ON categories(user_id, deleted_at, name);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL,
  category VARCHAR(120) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  currency VARCHAR(8),
  description VARCHAR(1000),
  merchant VARCHAR(255),
  source_text VARCHAR(1000),
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE INDEX idx_transactions_user_deleted_created_id ON transactions(user_id, deleted_at, created_at DESC, id DESC);
CREATE INDEX idx_transactions_user_deleted_date ON transactions(user_id, deleted_at, date);
CREATE INDEX idx_transactions_user_type_date ON transactions(user_id, type, date);
CREATE INDEX idx_transactions_user_category ON transactions(user_id, category);

CREATE TABLE budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  category VARCHAR(120) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  period_month VARCHAR(7) NOT NULL,
  color VARCHAR(40),
  icon VARCHAR(120),
  notes VARCHAR(500),
  active_key VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_budgets_user_category_month_active ON budgets(user_id, category, period_month, active_key);
CREATE INDEX idx_budgets_user_month_active ON budgets(user_id, period_month, deleted_at);
CREATE INDEX idx_budgets_user_category ON budgets(user_id, category);

CREATE TABLE goals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  title VARCHAR(120) NOT NULL,
  target_amount DECIMAL(18,2) NOT NULL,
  saved_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  target_date DATETIME,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  color VARCHAR(40),
  icon VARCHAR(120),
  notes VARCHAR(500),
  active_key VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_goals_user_title_active ON goals(user_id, title, active_key);
CREATE INDEX idx_goals_user_status_active ON goals(user_id, status, deleted_at);
CREATE INDEX idx_goals_user_target_date ON goals(user_id, target_date);
