DROP TABLE IF EXISTS budgets;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name VARCHAR(120) NOT NULL,
  type VARCHAR(20) NOT NULL,
  icon VARCHAR(120),
  color VARCHAR(40),
  description VARCHAR(500),
  is_default TINYINT DEFAULT 0,
  usage_count INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_categories_user_name_active ON categories(user_id, name, deleted_at);
CREATE INDEX idx_categories_user_deleted_name ON categories(user_id, deleted_at, name);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  type VARCHAR(20) NOT NULL,
  category VARCHAR(120) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  description VARCHAR(1000),
  date DATETIME DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE INDEX idx_transactions_user_deleted_created_id ON transactions(user_id, deleted_at, created_at DESC, id DESC);
CREATE INDEX idx_transactions_user_deleted_date ON transactions(user_id, deleted_at, date);
CREATE INDEX idx_transactions_user_type_date ON transactions(user_id, type, date);
CREATE INDEX idx_transactions_user_category ON transactions(user_id, category);

CREATE TABLE budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  category VARCHAR(120) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  period_month VARCHAR(7) NOT NULL,
  color VARCHAR(40),
  icon VARCHAR(120),
  notes VARCHAR(500),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME
);
CREATE UNIQUE INDEX uk_budgets_user_category_month_active ON budgets(user_id, category, period_month, deleted_at);
CREATE INDEX idx_budgets_user_month_active ON budgets(user_id, period_month, deleted_at);
CREATE INDEX idx_budgets_user_category ON budgets(user_id, category);
