-- Manual migration for AI provider call audit and token usage tracking.
--
-- MySQL:
-- CREATE TABLE ai_call_log (
--   id BIGINT PRIMARY KEY AUTO_INCREMENT,
--   user_id BIGINT NOT NULL,
--   operation VARCHAR(32) NOT NULL,
--   model VARCHAR(100),
--   base_url VARCHAR(255),
--   prompt_tokens INT,
--   completion_tokens INT,
--   total_tokens INT,
--   latency_ms INT,
--   success TINYINT NOT NULL,
--   error_code VARCHAR(64),
--   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE INDEX idx_ai_call_log_user_created ON ai_call_log(user_id, created_at);
--
-- H2:
-- CREATE TABLE IF NOT EXISTS ai_call_log (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   user_id BIGINT NOT NULL,
--   operation VARCHAR(32) NOT NULL,
--   model VARCHAR(100),
--   base_url VARCHAR(255),
--   prompt_tokens INT,
--   completion_tokens INT,
--   total_tokens INT,
--   latency_ms INT,
--   success TINYINT NOT NULL,
--   error_code VARCHAR(64),
--   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
-- );
-- CREATE INDEX IF NOT EXISTS idx_ai_call_log_user_created ON ai_call_log(user_id, created_at);

CREATE TABLE ai_call_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  operation VARCHAR(32) NOT NULL,
  model VARCHAR(100),
  base_url VARCHAR(255),
  prompt_tokens INT,
  completion_tokens INT,
  total_tokens INT,
  latency_ms INT,
  success TINYINT NOT NULL,
  error_code VARCHAR(64),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_ai_call_log_user_created ON ai_call_log(user_id, created_at);
